### ISSUE TITLE
Home footer

### ISSUE THREAD

**Issue by haniali1234** [geekwise-kao-thao/geekwise-academy#11]
page: footer
issure: height red background
photo:
your site: 
![screen shot 2016-04-13 at 8 14 47 am](https://cloud.githubusercontent.com/assets/11038599/14498684/26009128-0150-11e6-8285-4049ff7e3b2b.png)

GeekWise:
![screen shot 2016-04-13 at 8 17 35 am](https://cloud.githubusercontent.com/assets/11038599/14498693/350017a2-0150-11e6-8a27-4370658e5817.png)

**Comment by Alexg1021** [comment]
close it
