### ISSUE TITLE
Padding Issue

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-kao-thao/geekwise-academy#3]
page: cohort
issue: padding issue

how yours looks:
![screen shot 2016-03-18 at 3 49 06 pm](https://cloud.githubusercontent.com/assets/7436666/13894093/99228bd6-ed21-11e5-8020-d1ab8e4d988c.png)

how it should look:
![screen shot 2016-03-18 at 3 51 43 pm](https://cloud.githubusercontent.com/assets/7436666/13894079/69801416-ed21-11e5-84a0-0a28bd81f210.png)

option:
add some padding on the sides of the main content

**Comment by geekwise-kao-thao** [comment]
thank you.

corrected with width and centering.
