### ISSUE TITLE
sign up button on menu

### ISSUE THREAD

**Issue by ghost** [geekwise-kao-thao/geekwise-academy#4]
![screen shot 2016-03-18 at 6 31 48 pm](https://cloud.githubusercontent.com/assets/16930006/13895924/67f7b394-ed38-11e5-8a57-a6730f016abe.png)

**Comment by geekwise-kao-thao** [comment]
thank you for the issue.  increased font-weight to 600 and also increased font-size to match the rest of the items in the navbar.  

the image below, however, is a snip from the actual geekwiseacademy.com that shows the font-weight for "sign up" to be less than the rest of the items on the navbar, and its font-size is smaller too. 
![signup](https://cloud.githubusercontent.com/assets/17086853/13905357/d6f6a2f8-ee7a-11e5-8474-37ed07bb6003.PNG)
