### ISSUE TITLE
issue 1

### ISSUE THREAD

**Issue by haniali1234** [geekwise-kao-thao/geekwise-academy#5]
page: cohort
issue: the bird is missing mobile view
photo:
![screen shot 2016-03-29 at 9 42 18 pm](https://cloud.githubusercontent.com/assets/11038599/14132152/5c850cba-f5f7-11e5-8e9a-fb6b1d23e288.png)

**Comment by geekwise-kao-thao** [comment]
thanks for noticing, but their bird is missing too. 

photo:

![image](https://cloud.githubusercontent.com/assets/17086853/14142370/251d22f6-f63a-11e5-94a8-73cf8ac9f1ea.png)

**Comment by geekwise-kao-thao** [comment]
disregard my last comment

**Comment by geekwise-kao-thao** [comment]
fixed issue.  thank you
