### ISSUE TITLE
CSS - Mobile - Menu

### ISSUE THREAD

**Issue by geekwise** [geekwise-kao-thao/geekwise-academy#7]
Page: Signup
Issue: @geekwise-kao-thao  The GeekwiseAcademy.com site does **not** have the responsive menu on the signup page - I am aware of that. Because this will be used in a portfolio - it's my personal recommendation to add it back in. A client _may think it's broken_

<img width="579" alt="sign" src="https://cloud.githubusercontent.com/assets/14043285/14230481/9bf4513e-f90e-11e5-8c8e-ed09a81a0f2c.png">

**Comment by geekwise-kao-thao** [comment]
responsive menu added to signup page

**Comment by Alexg1021** [comment]
cool close it
