### ISSUE TITLE
CSS - Courses - Signup Details

### ISSUE THREAD

**Issue by geekwise** [geekwise-kao-thao/geekwise-academy#8]
Page: Courses
Issue: Several small details.
- Signup Text Menu On The Top --> Font not bold for menu
- Nav Menu button is not white border
- Nav Menu button is larger than original site
- Nav Menu button needs grey bars inside / not black
- Missing Greyed out text CSS Class for  `.sold-out`
- Missing course name bold text

![screen shot 2016-04-02 at 8 06 31 pm](https://cloud.githubusercontent.com/assets/14043285/14230574/db14464a-f912-11e5-8fa4-195f7cda9696.png)

**Comment by geekwise-kao-thao** [comment]
updated

**Comment by Alexg1021** [comment]
cool. close it
